### ISSUE TITLE
Flaky test failures

### ISSUE THREAD

**Issue by hden** [hden/node-serf#21]
Unstable test results from query+stream+respond, possibly race conditions.

**Comment by zbjornson** [comment]
The current API provides no way to wait for a stream from the stream/query/monitor commands to begin, which is why there are `setTimeout`s in a few tests where we need to issue some command after listening for it from the other worker. I propse changing the API to follow node's typical pattern:

* Change the callback function to be 'onSubscribe'; users will have to use `stream.on(...)` listeners. Also emit an event, maybe called 'listen' or 'subscribe'.
```js
var stream = client.stream(params, onSubscribe)
stream.on('data', ...)
stream.on('listen', onSubscribe)
```

Precedence: [node's net.server.listen pattern](https://nodejs.org/dist/latest-v6.x/docs/api/net.html#net_server_listen_handle_backlog_callback), [node's udp socket bind](https://nodejs.org/dist/latest-v6.x/docs/api/dgram.html#dgram_socket_bind_options_callback)

**Comment by zbjornson** [comment]
This is not a race condition after all. The Serf agent is sending some unexpected responses. Reported upstream: hashicorp/serf#408.

Simple solution for us for now is adding a guard clause when accessing the response.
